# AI Fight Analyzer - Camera Package

from app.camera.adb_forwarder import (
    AdbDevice,
    AdbDeviceNotFoundError,
    AdbError,
    AdbForwardError,
    AdbNotFoundError,
    DualAdbSetupResult,
    find_adb_executable,
    get_active_serials,
    list_devices,
    list_forwards,
    remove_forward,
    setup_dual_droidcam_usb,
    setup_forward,
    teardown_dual_droidcam_usb,
    verify_endpoint,
)
from app.camera.camera_manager import (
    CameraInfo,
    DiscoveryResult,
    check_droidcam_port,
    discover_cameras,
    discover_droidcam_streams,
    probe_stream,
)
from app.camera.recorder import (
    DEFAULT_FRONT_URL,
    DEFAULT_ROTATION,
    DEFAULT_SIDE_URL,
    TARGET_FPS,
    TARGET_HEIGHT,
    TARGET_WIDTH,
    CameraConfig,
    CameraResult,
    CameraRole,
    DualCameraRecorder,
    RecordingSession,
    rotate_frame,
)

__all__ = [
    # Camera discovery
    "CameraInfo",
    "DiscoveryResult",
    "check_droidcam_port",
    "discover_cameras",
    "discover_droidcam_streams",
    "probe_stream",
    # ADB forwarding
    "AdbDevice",
    "AdbError",
    "AdbNotFoundError",
    "AdbDeviceNotFoundError",
    "AdbForwardError",
    "DualAdbSetupResult",
    "find_adb_executable",
    "list_devices",
    "get_active_serials",
    "list_forwards",
    "setup_forward",
    "remove_forward",
    "verify_endpoint",
    "setup_dual_droidcam_usb",
    "teardown_dual_droidcam_usb",
    # Dual camera recorder
    "DEFAULT_FRONT_URL",
    "DEFAULT_SIDE_URL",
    "TARGET_WIDTH",
    "TARGET_HEIGHT",
    "TARGET_FPS",
    "DEFAULT_ROTATION",
    "CameraConfig",
    "CameraResult",
    "CameraRole",
    "DualCameraRecorder",
    "RecordingSession",
    "rotate_frame",
]
